project_id = "hfdwqfsdwukjcjrrewpn"

[functions.help-assistant]
verify_jwt = false

[functions.insert-ncert-solutions]
verify_jwt = false

[functions.concept-explainer]
verify_jwt = false

[functions.chess-assistant]
verify_jwt = false
